# name: Run a notebook in databricks

# on:
#  push:

# jobs:
#  run-databricks-notebook:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v2
#      - name: Install databricks CLI
#        run: |
#          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

#      - name: Databricks CLI version
#        run: databricks --version
#      - name: Run a databricks notebook
#        uses: databricks/run-notebook@v0
#        with:
#          local-notebook-path: .github/workflows/dabdemo_notebook.py
#          databricks-host: https://dbc-11df7ca4-5026.cloud.databricks.com
#          databricks-token: dapi2f98369b849c3790a880a6a9e4748434 
#                            # ${{ secrets.DATABRICKS_TOKEN }}
#          new-cluster-json: >
#            {
#              "num_workers": 1,
#              "spark_version": "10.4.x-scala2.12",
#              "node_type_id": "m5d.large"
#            }
